apiVersion: v1
kind: ServiceAccount
metadata:
  name: jupyter-sa
  namespace: jupyter
---
# List of Permissions
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: jupyter-cluster-role
 namespace: jupyter
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list", "edit", "create", "delete"]
---
# Attach the K8s ClusterRole to our K8s ServiceAccount
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jupyter-role-binding
  namespace: jupyter
subjects:
- kind: ServiceAccount
  name: jupyter-sa
  namespace: jupyter
roleRef:
  kind: ClusterRole
  name: jupyter-cluster-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter
  namespace: jupyter
spec:
  selector:
    matchLabels:
      app: jupyter
  replicas: 1
  template:
    metadata:
      labels:
        app: jupyter
    spec:
      serviceAccountName: jupyter-sa
      containers:
      - name: server
        image: "jupyter/all-spark-notebook:latest"
        ports:
        - name: jupyter-port
          containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: jupyter
  namespace: jupyter
  labels:
    app: jupyter
spec:
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: jupyter-port
  selector:
    app: jupyter
